# Site Settings
locale                   : "de_DE"
title                    : "Rainer Milczewski"
#title_separator          : "-"
#name                     : &name "Your Name"
#description              : &description "personal description"

# Theme
theme: jekyll-theme-cayman
